/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package juego;

import java.io.File;
import javax.sound.sampled.AudioSystem;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import poo.proyecto2.tirviatest.Jugador;
import poo.proyecto2.triviaquirk.excepciones.excepcionPartidaNoDisponible;
import poo.proyecto2.triviaquirk.excepciones.excepcionPreguntasNoDisponibles;
import poo.proyecto2.triviaquirk.excepciones.excepcionRangoMayor;
import poo.proyecto2.triviaquirk.iJugador;
import poo.proyecto2.triviaquirk.iPregunta;

/**
 * La clase Inicio representa la ventana principal del juego y proporciona
 * funcionalidad para la configuración inicial del juego, incluida la selección
 * del número de jugadores y las categorías de preguntas.
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Clip para reproducir efectos de sonido.
     */
    /**
     * Clip para reproducir música de fondo.
     */
    public static Process procesoMusica;
    /**
     * Ruta base para los archivos de sonido.
     * 
     */
    public String ruta = rutaAsset("Sounds/");
    /**
     * Lista de nombres de archivos de sonido.
     */
    public static ArrayList<String> lista = new ArrayList<String>();
    /**
     * Número de jugadores en el juego.
     */
    public static byte numeroJugadores;
    /**
     * Mapa que almacena preguntas organizadas por categoría.
     */
    public static Map<String, ArrayList<iPregunta>> PreguntasPorCategoria = null;
    /**
     * Lista de jugadores en el juego.
     */
    public static ArrayList<iJugador> listaJugadores = new ArrayList<iJugador>();
    /**
     * Índice del jugador actual en la lista de jugadores.
     */
    public static byte jugadorActual = 0;
    
    public static Long pidMusica = null;
    
    
    private String rutaAsset(String rutaRelativa) {
    return System.getProperty("user.dir") + "/src/main/java/assets/" + rutaRelativa;
}

private javax.swing.ImageIcon icono(String rutaRelativa) {
    String rutaCompleta = rutaAsset(rutaRelativa);
    java.io.File archivo = new java.io.File(rutaCompleta);

    if (!archivo.exists()) {
        System.out.println("No se encontró la imagen: " + rutaCompleta);
    }

    return new javax.swing.ImageIcon(rutaCompleta);
}

    /**
     * Constructor de la clase Inicio que inicializa los componentes de la
     * interfaz gráfica y configura la pantalla de inicio del juego.
     */
    public Inicio() {
       
        initComponents();
        setIconImage(icono("icon.png").getImage());
        setTitle("TriviaQuirk");
        paises.setVisible(false);
        cine.setVisible(false);
        culturaGeneral.setVisible(false);
        sorpresa.setVisible(false);
        eligeLasCategorias.setVisible(false);
        empezar.setVisible(false);
        atras.setVisible(false);
        dosJugadores.setVisible(false);
        tresJugadores.setVisible(false);
        cuatroJugadores.setVisible(false);
        cuantosJugadores.setVisible(false);
        music("SoundIntro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
private void initComponents() {
    
    dosJugadores = new javax.swing.JButton();
    tresJugadores = new javax.swing.JButton();
    cuatroJugadores = new javax.swing.JButton();
    atras = new javax.swing.JButton();
    cuantosJugadores = new javax.swing.JLabel();
    empezar = new javax.swing.JButton();
    paises = new javax.swing.JButton();
    cine = new javax.swing.JButton();
    culturaGeneral = new javax.swing.JButton();
    sorpresa = new javax.swing.JButton();
    eligeLasCategorias = new javax.swing.JLabel();
    unJugador = new javax.swing.JButton();
    multijugador = new javax.swing.JButton();
    salir = new javax.swing.JButton();
    logo = new javax.swing.JLabel();
    fondo = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(1270, 630));
    setResizable(false);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    dosJugadores.setIcon(icono("Pantalla Multijugador/2.png"));
    dosJugadores.setBorderPainted(false);
    dosJugadores.setContentAreaFilled(false);
    dosJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    dosJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    dosJugadores.setRolloverIcon(icono("Pantalla Multijugador/2 selec.png"));
    dosJugadores.setRolloverSelectedIcon(icono("Pantalla Multijugador/2 selec.png"));
    dosJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            dosJugadoresMouseEntered(evt);
        }
    });
    dosJugadores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            dosJugadoresActionPerformed(evt);
        }
    });
    getContentPane().add(dosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 200));

    tresJugadores.setIcon(icono("Pantalla Multijugador/3.png"));
    tresJugadores.setBorderPainted(false);
    tresJugadores.setContentAreaFilled(false);
    tresJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    tresJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    tresJugadores.setRolloverIcon(icono("Pantalla Multijugador/3 selec.png"));
    tresJugadores.setRolloverSelectedIcon(icono("Pantalla Multijugador/3 selec.png"));
    tresJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            tresJugadoresMouseEntered(evt);
        }
    });
    tresJugadores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tresJugadoresActionPerformed(evt);
        }
    });
    getContentPane().add(tresJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 180, 200));

    cuatroJugadores.setIcon(icono("Pantalla Multijugador/4.png"));
    cuatroJugadores.setBorderPainted(false);
    cuatroJugadores.setContentAreaFilled(false);
    cuatroJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cuatroJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    cuatroJugadores.setRolloverIcon(icono("Pantalla Multijugador/4 selec.png"));
    cuatroJugadores.setRolloverSelectedIcon(icono("Pantalla Multijugador/4 selec.png"));
    cuatroJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            cuatroJugadoresMouseEntered(evt);
        }
    });
    cuatroJugadores.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cuatroJugadoresActionPerformed(evt);
        }
    });
    getContentPane().add(cuatroJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 180, 200));

    atras.setIcon(icono("atras.png"));
    atras.setBorderPainted(false);
    atras.setContentAreaFilled(false);
    atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    atras.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            atrasMouseEntered(evt);
        }
    });
    atras.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            atrasActionPerformed(evt);
        }
    });
    getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

    cuantosJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    cuantosJugadores.setIcon(icono("Pantalla Multijugador/Jugadores.png"));
    cuantosJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    cuantosJugadores.setVerifyInputWhenFocusTarget(false);
    getContentPane().add(cuantosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 1270, -1));
    cuantosJugadores.getAccessibleContext().setAccessibleName("");

    empezar.setIcon(icono("Un Jugador/Empezar.png"));
    empezar.setBorder(null);
    empezar.setBorderPainted(false);
    empezar.setContentAreaFilled(false);
    empezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    empezar.setRolloverIcon(icono("Un Jugador/Empezar Cursor.png"));
    empezar.setRolloverSelectedIcon(icono("Un Jugador/Empezar Cursor.png"));
    empezar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            empezarMouseEntered(evt);
        }
    });
    empezar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            empezarActionPerformed(evt);
        }
    });
    getContentPane().add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 330, 90));

    paises.setIcon(icono("Un Jugador/Normal Buttons/Paises.png"));
    paises.setBorder(null);
    paises.setBorderPainted(false);
    paises.setContentAreaFilled(false);
    paises.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    paises.setFocusPainted(false);
    paises.setRolloverIcon(icono("Un Jugador/Cursor/Paises_Cursor.png"));
    paises.setRolloverSelectedIcon(icono("Un Jugador/Cursor/Paises_Cursor.png"));
    paises.setSelectedIcon(icono("Un Jugador/Select/Paises_Selec.png"));
    paises.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            paisesMouseEntered(evt);
        }
    });
    paises.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            paisesActionPerformed(evt);
        }
    });
    getContentPane().add(paises, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 510, 160));

    cine.setIcon(icono("Un Jugador/Normal Buttons/Cine.png"));
    cine.setBorder(null);
    cine.setBorderPainted(false);
    cine.setContentAreaFilled(false);
    cine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    cine.setFocusPainted(false);
    cine.setRolloverIcon(icono("Un Jugador/Cursor/Cine_Cursor.png"));
    cine.setRolloverSelectedIcon(icono("Un Jugador/Cursor/Cine_Cursor.png"));
    cine.setSelectedIcon(icono("Un Jugador/Select/Cine_Selec.png"));
    cine.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            cineMouseEntered(evt);
        }
    });
    cine.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cineActionPerformed(evt);
        }
    });
    getContentPane().add(cine, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 510, 160));

    culturaGeneral.setIcon(icono("Un Jugador/Normal Buttons/Cultura General.png"));
    culturaGeneral.setBorder(null);
    culturaGeneral.setBorderPainted(false);
    culturaGeneral.setContentAreaFilled(false);
    culturaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    culturaGeneral.setFocusPainted(false);
    culturaGeneral.setRolloverIcon(icono("Un Jugador/Cursor/Cultura_General_Cursor.png"));
    culturaGeneral.setRolloverSelectedIcon(icono("Un Jugador/Cursor/Cultura_General_Cursor.png"));
    culturaGeneral.setSelectedIcon(icono("Un Jugador/Select/Cultura_General_Selec.png"));
    culturaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            culturaGeneralMouseEntered(evt);
        }
    });
    culturaGeneral.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            culturaGeneralActionPerformed(evt);
        }
    });
    getContentPane().add(culturaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 510, 160));

    sorpresa.setIcon(icono("Un Jugador/Normal Buttons/Sorpresa.png"));
    sorpresa.setBorder(null);
    sorpresa.setBorderPainted(false);
    sorpresa.setContentAreaFilled(false);
    sorpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    sorpresa.setFocusPainted(false);
    sorpresa.setRolloverIcon(icono("Un Jugador/Cursor/Sorpresa_Curso.png"));
    sorpresa.setRolloverSelectedIcon(icono("Un Jugador/Cursor/Sorpresa_Curso.png"));
    sorpresa.setSelectedIcon(icono("Un Jugador/Select/Sorpresa_Selec.png"));
    sorpresa.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            sorpresaMouseEntered(evt);
        }
    });
    sorpresa.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            sorpresaActionPerformed(evt);
        }
    });
    getContentPane().add(sorpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 510, 160));

    eligeLasCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    eligeLasCategorias.setIcon(icono("Un Jugador/Elige_las_categorias.png"));
    eligeLasCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    getContentPane().add(eligeLasCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 1270, -1));

    unJugador.setIcon(icono("Pantalla Inicio/Jugar.png"));
    unJugador.setBorder(null);
    unJugador.setBorderPainted(false);
    unJugador.setContentAreaFilled(false);
    unJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    unJugador.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
    unJugador.setRolloverIcon(icono("Pantalla Inicio/Jugar_selec.png"));
    unJugador.setRolloverSelectedIcon(icono("Pantalla Inicio/Jugar_selec.png"));
    unJugador.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            unJugadorMouseEntered(evt);
        }
    });
    unJugador.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            unJugadorActionPerformed(evt);
        }
    });
    getContentPane().add(unJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 350, 120));
    unJugador.getAccessibleContext().setAccessibleDescription("");

    multijugador.setIcon(icono("Pantalla Inicio/Multijugador.png"));
    multijugador.setBorder(null);
    multijugador.setBorderPainted(false);
    multijugador.setContentAreaFilled(false);
    multijugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    multijugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    multijugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    multijugador.setRolloverIcon(icono("Pantalla Inicio/Multijugador_selec.png"));
    multijugador.setRolloverSelectedIcon(icono("Pantalla Inicio/Multijugador_selec.png"));
    multijugador.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    multijugador.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            multijugadorMouseEntered(evt);
        }
    });
    multijugador.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            multijugadorActionPerformed(evt);
        }
    });
    getContentPane().add(multijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 370, 120));

    salir.setIcon(icono("Pantalla Inicio/Cerrar.png"));
    salir.setBorder(null);
    salir.setBorderPainted(false);
    salir.setContentAreaFilled(false);
    salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    salir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    salir.setRolloverIcon(icono("Pantalla Inicio/Cerrar_selec.png"));
    salir.setRolloverSelectedIcon(icono("Pantalla Inicio/Cerrar_selec.png"));
    salir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    salir.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            salirMouseEntered(evt);
        }
    });
    salir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            salirActionPerformed(evt);
            
        }
    });
    getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 360, 120));

    logo.setIcon(icono("Logo-animado.gif"));
    getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

    fondo.setIcon(icono("Fondo Animado.gif"));
    getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1270, 630));

    pack();
}// </editor-fold>
   /* @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dosJugadores = new javax.swing.JButton();
        tresJugadores = new javax.swing.JButton();
        cuatroJugadores = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        cuantosJugadores = new javax.swing.JLabel();
        empezar = new javax.swing.JButton();
        paises = new javax.swing.JButton();
        cine = new javax.swing.JButton();
        culturaGeneral = new javax.swing.JButton();
        sorpresa = new javax.swing.JButton();
        eligeLasCategorias = new javax.swing.JLabel();
        unJugador = new javax.swing.JButton();
        multijugador = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1270, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dosJugadores.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\2.png"));
        dosJugadores.setBorderPainted(false);
        dosJugadores.setContentAreaFilled(false);
        dosJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dosJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dosJugadores.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\2 selec.png"));
        dosJugadores.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\2 selec.png"));
        dosJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dosJugadoresMouseEntered(evt);
            }
        });
        dosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(dosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 180, 200));

        tresJugadores.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\3.png"));
        tresJugadores.setBorderPainted(false);
        tresJugadores.setContentAreaFilled(false);
        tresJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tresJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tresJugadores.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\3 selec.png"));
        tresJugadores.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\3 selec.png"));
        tresJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tresJugadoresMouseEntered(evt);
            }
        });
        tresJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(tresJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 180, 200));

        cuatroJugadores.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\4.png"));
        cuatroJugadores.setBorderPainted(false);
        cuatroJugadores.setContentAreaFilled(false);
        cuatroJugadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatroJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuatroJugadores.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\4 selec.png"));
        cuatroJugadores.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\4 selec.png"));
        cuatroJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cuatroJugadoresMouseEntered(evt);
            }
        });
        cuatroJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroJugadoresActionPerformed(evt);
            }
        });
        getContentPane().add(cuatroJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 180, 200));

        atras.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\atras.png"));
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                atrasMouseEntered(evt);
            }
        });
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        cuantosJugadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cuantosJugadores.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Multijugador\\Jugadores.png"));
        cuantosJugadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cuantosJugadores.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(cuantosJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 1270, -1));
        cuantosJugadores.getAccessibleContext().setAccessibleName("");

        empezar.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Empezar.png"));
        empezar.setBorder(null);
        empezar.setBorderPainted(false);
        empezar.setContentAreaFilled(false);
        empezar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        empezar.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Empezar Cursor.png"));
        empezar.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Empezar Cursor.png"));
        empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                empezarMouseEntered(evt);
            }
        });
        empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarActionPerformed(evt);
            }
        });
        getContentPane().add(empezar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 330, 90));

        paises.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Normal Buttons\\Paises.png"));
        paises.setBorder(null);
        paises.setBorderPainted(false);
        paises.setContentAreaFilled(false);
        paises.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paises.setFocusPainted(false);
        paises.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Paises_Cursor.png"));
        paises.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Paises_Cursor.png"));
        paises.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Select\\Paises_Selec.png"));
        paises.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paisesMouseEntered(evt);
            }
        });
        paises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisesActionPerformed(evt);
            }
        });
        getContentPane().add(paises, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 510, 160));

        cine.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Normal Buttons\\Cine.png"));
        cine.setBorder(null);
        cine.setBorderPainted(false);
        cine.setContentAreaFilled(false);
        cine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cine.setFocusPainted(false);
        cine.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Cine_Cursor.png"));
        cine.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Cine_Cursor.png"));
        cine.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Select\\Cine_Selec.png"));
        cine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cineMouseEntered(evt);
            }
        });
        cine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cineActionPerformed(evt);
            }
        });
        getContentPane().add(cine, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 510, 160));

        culturaGeneral.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Normal Buttons\\Cultura General.png"));
        culturaGeneral.setBorder(null);
        culturaGeneral.setBorderPainted(false);
        culturaGeneral.setContentAreaFilled(false);
        culturaGeneral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        culturaGeneral.setFocusPainted(false);
        culturaGeneral.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Cultura_General_Cursor.png"));
        culturaGeneral.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Cultura_General_Cursor.png"));
        culturaGeneral.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Select\\Cultura_General_Selec.png"));
        culturaGeneral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                culturaGeneralMouseEntered(evt);
            }
        });
        culturaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                culturaGeneralActionPerformed(evt);
            }
        });
        getContentPane().add(culturaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 510, 160));

        sorpresa.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Normal Buttons\\Sorpresa.png"));
        sorpresa.setBorder(null);
        sorpresa.setBorderPainted(false);
        sorpresa.setContentAreaFilled(false);
        sorpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sorpresa.setFocusPainted(false);
        sorpresa.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Sorpresa_Curso.png"));
        sorpresa.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Cursor\\Sorpresa_Curso.png"));
        sorpresa.setSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Select\\Sorpresa_Selec.png"));
        sorpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sorpresaMouseEntered(evt);
            }
        });
        sorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorpresaActionPerformed(evt);
            }
        });
        getContentPane().add(sorpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 510, 160));

        eligeLasCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eligeLasCategorias.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Un Jugador\\Elige_las_categorias.png"));
        eligeLasCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(eligeLasCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 1270, -1));

        unJugador.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Jugar.png"));
        unJugador.setBorder(null);
        unJugador.setBorderPainted(false);
        unJugador.setContentAreaFilled(false);
        unJugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unJugador.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        unJugador.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Jugar_selec.png"));
        unJugador.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Jugar_selec.png"));
        unJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unJugadorMouseEntered(evt);
            }
        });
        unJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(unJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, 350, 120));
        unJugador.getAccessibleContext().setAccessibleDescription("");

        multijugador.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Multijugador.png"));
        multijugador.setBorder(null);
        multijugador.setBorderPainted(false);
        multijugador.setContentAreaFilled(false);
        multijugador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multijugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        multijugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multijugador.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Multijugador_selec.png"));
        multijugador.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Multijugador_selec.png"));
        multijugador.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        multijugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                multijugadorMouseEntered(evt);
            }
        });
        multijugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multijugadorActionPerformed(evt);
            }
        });
        getContentPane().add(multijugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 300, 370, 120));

        salir.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Cerrar.png"));
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salir.setRolloverIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Cerrar_selec.png"));
        salir.setRolloverSelectedIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Pantalla Inicio\\Cerrar_selec.png"));
        salir.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salirMouseEntered(evt);
            }
        });
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 360, 120));

        logo.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Logo-animado.gif"));
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") + "\\src\\main\\java\\assets\\Fondo Animado.gif"));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1270, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    */
    /**
     * Maneja el evento de un jugador seleccionando el modo de juego de un
     * jugador. Oculta elementos no necesarios y muestra las opciones de
     * categorías y el botón de empezar.
     *
     * @param evt Evento generado por el botón unJugador.
     */

    private void unJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unJugadorActionPerformed
        logo.setVisible(false);
        salir.setVisible(false);
        multijugador.setVisible(false);
        unJugador.setVisible(false);
        empezar.setVisible(true);
        eligeLasCategorias.setVisible(true);
        sorpresa.setVisible(true);
        cine.setVisible(true);
        culturaGeneral.setVisible(true);
        paises.setVisible(true);
        atras.setVisible(true);
        this.numeroJugadores = 1;
        this.listaJugadores.add(new Jugador("Jugador " + 0));
    }//GEN-LAST:event_unJugadorActionPerformed
    /**
     * Maneja el evento de selección del modo multijugador. Oculta elementos no
     * necesarios y muestra las opciones de número de jugadores y el botón de
     * atrás.
     *
     * @param evt Evento generado por el botón multijugador.
     */
    private void multijugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multijugadorActionPerformed
        // TODO add your handling code here:
        logo.setVisible(false);
        salir.setVisible(false);
        multijugador.setVisible(false);
        unJugador.setVisible(false);
        dosJugadores.setVisible(true);
        tresJugadores.setVisible(true);
        cuatroJugadores.setVisible(true);
        cuantosJugadores.setVisible(true);
        atras.setVisible(true);

    }//GEN-LAST:event_multijugadorActionPerformed
    /**
     * Maneja el evento de selección/deselección del botón de sorpresa.
     * Actualiza la lista de categorías seleccionadas.
     *
     * @param evt Evento generado por el botón sorpresa.
     */
    private void sorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorpresaActionPerformed
        if (sorpresa.isSelected()) {
            sorpresa.setSelected(false);
            lista.remove("Sorpresa");
        } else {
            sorpresa.setSelected(true);
            lista.add("Sorpresa");
        }
    }//GEN-LAST:event_sorpresaActionPerformed
    /**
     * Maneja el evento de selección/deselección del botón de cultura general.
     * Actualiza la lista de categorías seleccionadas.
     *
     * @param evt Evento generado por el botón culturaGeneral.
     */
    private void culturaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_culturaGeneralActionPerformed
        if (culturaGeneral.isSelected()) {
            culturaGeneral.setSelected(false);
            lista.remove("General");
        } else {
            culturaGeneral.setSelected(true);
            lista.add("General");
        }
    }//GEN-LAST:event_culturaGeneralActionPerformed
    /**
     * Maneja el evento de selección/deselección del botón de cine. Actualiza la
     * lista de categorías seleccionadas.
     *
     * @param evt Evento generado por el botón cine.
     */
    private void cineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cineActionPerformed
        if (cine.isSelected()) {
            cine.setSelected(false);
            lista.remove("Cine");
        } else {
            cine.setSelected(true);
            lista.add("Cine");
        }
    }//GEN-LAST:event_cineActionPerformed
    /**
     * Maneja el evento de selección/deselección del botón de países. Actualiza
     * la lista de categorías seleccionadas.
     *
     * @param evt Evento generado por el botón paises.
     */
    private void paisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisesActionPerformed
        if (paises.isSelected()) {
            paises.setSelected(false);
            lista.remove("Paises");
        } else {
            paises.setSelected(true);
            lista.add("Paises");
        }
    }//GEN-LAST:event_paisesActionPerformed
    /**
     * Maneja el evento de clic en el botón de empezar juego. Detiene la música
     * de fondo, oculta la ventana actual y crea una nueva instancia de la clase
     * Juegos para comenzar el juego.
     *
     * @param evt Evento generado por el botón empezar.
     */
    private void empezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarActionPerformed
        if (paises.isSelected() || cine.isSelected() || culturaGeneral.isSelected() || sorpresa.isSelected()) {

            detenerMusica();
            setVisible(false);
            Juegos juego;
            if (PreguntasPorCategoria == null) {
                try {
                    PreguntasPorCategoria = Juegos.ElegirPreguntas(this.lista);
                } catch (excepcionPreguntasNoDisponibles ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            try {
                juego = new Juegos();
                juego.setVisible(true);
            } catch (excepcionPreguntasNoDisponibles ex) {
                Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_empezarActionPerformed
    /**
     * Maneja el evento de clic en el botón "Salir". Cierra la aplicación al
     * invocar el método System.exit(0).
     *
     * @param evt Evento generado por el botón salir.
     */
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        detenerMusica();
        
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed
    /**
     * Maneja el evento de entrada del ratón al botón "Salir". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón salir.
     */
    private void salirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_salirMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Multijugador". Reproduce
     * un sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón
     * multijugador.
     */
    private void multijugadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multijugadorMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_multijugadorMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Un Jugador". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón unJugador.
     */
    private void unJugadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unJugadorMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_unJugadorMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Sorpresa". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón sorpresa.
     */
    private void sorpresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sorpresaMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_sorpresaMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Cultura General".
     * Reproduce un sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón
     * culturaGeneral.
     */
    private void culturaGeneralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_culturaGeneralMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_culturaGeneralMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Cine". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón cine.
     */
    private void cineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cineMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_cineMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Paises". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón paises.
     */
    private void paisesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paisesMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_paisesMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Empezar". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón empezar.
     */
    private void empezarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_empezarMouseEntered

    /**
     * Maneja el evento de clic en el botón "Atrás". Restablece la interfaz a la
     * pantalla de inicio ocultando las opciones de jugador. Reproduce un sonido
     * al presionar el botón.
     *
     * @param evt Evento generado por el botón atras.
     */
    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
        logo.setVisible(true);
        salir.setVisible(true);
        multijugador.setVisible(true);
        unJugador.setVisible(true);
        empezar.setVisible(false);
        eligeLasCategorias.setVisible(false);
        sorpresa.setVisible(false);
        cine.setVisible(false);
        culturaGeneral.setVisible(false);
        paises.setVisible(false);
        dosJugadores.setVisible(false);
        tresJugadores.setVisible(false);
        cuatroJugadores.setVisible(false);
        cuantosJugadores.setVisible(false);
        atras.setVisible(false);
        sonido("correct");

    }//GEN-LAST:event_atrasActionPerformed

    /**
     * Maneja el evento de clic en el botón "Tres Jugadores". Agrega tres
     * jugadores a la lista y muestra las opciones de categorías.
     *
     * @param evt Evento generado por el botón tresJugadores.
     */
    private void tresJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresJugadoresActionPerformed

        for (byte o = 0; o < 3; o++) {
            this.listaJugadores.add(new Jugador("Jugador " + o));
        }

        dosJugadores.setVisible(false);
        tresJugadores.setVisible(false);
        cuatroJugadores.setVisible(false);
        cuantosJugadores.setVisible(false);
        logo.setVisible(false);
        salir.setVisible(false);
        multijugador.setVisible(false);
        unJugador.setVisible(false);
        empezar.setVisible(true);
        eligeLasCategorias.setVisible(true);
        sorpresa.setVisible(true);
        cine.setVisible(true);
        culturaGeneral.setVisible(true);
        paises.setVisible(true);
        atras.setVisible(true);
        this.jugadorActual = 2;
    }//GEN-LAST:event_tresJugadoresActionPerformed
    /**
     * Maneja el evento de clic en el botón "Dos Jugadores". Agrega dos
     * jugadores a la lista y muestra las opciones de categorías.
     *
     * @param evt Evento generado por el botón dosJugadores.
     */
    private void dosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosJugadoresActionPerformed
        for (byte o = 1; o < 3; o++) {
            this.listaJugadores.add(new Jugador("Jugador " + o));
        }

        dosJugadores.setVisible(false);
        tresJugadores.setVisible(false);
        cuatroJugadores.setVisible(false);
        cuantosJugadores.setVisible(false);
        logo.setVisible(false);
        salir.setVisible(false);
        multijugador.setVisible(false);
        unJugador.setVisible(false);
        empezar.setVisible(true);
        eligeLasCategorias.setVisible(true);
        sorpresa.setVisible(true);
        cine.setVisible(true);
        culturaGeneral.setVisible(true);
        paises.setVisible(true);
        atras.setVisible(true);
        this.jugadorActual = 2;
    }//GEN-LAST:event_dosJugadoresActionPerformed
    /**
     * Maneja el evento de clic en el botón "Cuatro Jugadores". Agrega cuatro
     * jugadores a la lista y muestra las opciones de categorías.
     *
     * @param evt Evento generado por el botón cuatroJugadores.
     */
    private void cuatroJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroJugadoresActionPerformed
        for (byte o = 1; o < 5; o++) {
            this.listaJugadores.add(new Jugador("Jugador " + o));

        }
        dosJugadores.setVisible(false);
        tresJugadores.setVisible(false);
        cuatroJugadores.setVisible(false);
        cuantosJugadores.setVisible(false);
        logo.setVisible(false);
        salir.setVisible(false);
        multijugador.setVisible(false);
        unJugador.setVisible(false);
        empezar.setVisible(true);
        eligeLasCategorias.setVisible(true);
        sorpresa.setVisible(true);
        cine.setVisible(true);
        culturaGeneral.setVisible(true);
        paises.setVisible(true);
        atras.setVisible(true);
        this.jugadorActual = 4;
    }//GEN-LAST:event_cuatroJugadoresActionPerformed
    /**
     * Maneja el evento de entrada del ratón al botón "Dos Jugadores". Reproduce
     * un sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón
     * dosJugadores.
     */
    private void dosJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosJugadoresMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_dosJugadoresMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Tres Jugadores".
     * Reproduce un sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón
     * tresJugadores.
     */
    private void tresJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresJugadoresMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_tresJugadoresMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Cuatro Jugadores".
     * Reproduce un sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón
     * cuatroJugadores.
     */
    private void cuatroJugadoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroJugadoresMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_cuatroJugadoresMouseEntered
    /**
     * Maneja el evento de entrada del ratón al botón "Atrás". Reproduce un
     * sonido al entrar en el área del botón.
     *
     * @param evt Evento generado por la entrada del ratón al botón atras.
     */
    private void atrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atrasMouseEntered
        // TODO add your handling code here:
        sonido("Clickwav");
    }//GEN-LAST:event_atrasMouseEntered

    
   public void detenerMusica() {
    try {
        if (Inicio.pidMusica != null) {
            new ProcessBuilder(
                    "flatpak-spawn", "--host",
                    "kill", "-9", String.valueOf(Inicio.pidMusica)
            ).start().waitFor();

            Inicio.pidMusica = null;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * Reproduce música a partir de un archivo de sonido especificado. Configura
     * el bucle antes de iniciar el clip de sonido.
     *
     * @param archivo Nombre del archivo de sonido sin la extensión (.wav).
     */
   public void music(String archivo) {
    try {
        detenerMusica();

        String rutaArchivo = ruta + archivo + ".wav";

        Process p = new ProcessBuilder(
                "flatpak-spawn", "--host",
                "bash", "-lc",
                "paplay \"" + rutaArchivo + "\" >/dev/null 2>&1 & echo $!"
        ).start();

        java.io.BufferedReader reader = new java.io.BufferedReader(
                new java.io.InputStreamReader(p.getInputStream())
        );

        String pidTexto = reader.readLine();

        if (pidTexto != null && !pidTexto.isBlank()) {
            Inicio.pidMusica = Long.parseLong(pidTexto.trim());
        }

    } catch (Exception e1) {
        try {
            detenerMusica();

            String rutaArchivo = ruta + archivo + ".wav";

            Process p = new ProcessBuilder(
                    "flatpak-spawn", "--host",
                    "bash", "-lc",
                    "aplay -q \"" + rutaArchivo + "\" >/dev/null 2>&1 & echo $!"
            ).start();

            java.io.BufferedReader reader = new java.io.BufferedReader(
                    new java.io.InputStreamReader(p.getInputStream())
            );

            String pidTexto = reader.readLine();

            if (pidTexto != null && !pidTexto.isBlank()) {
                Inicio.pidMusica = Long.parseLong(pidTexto.trim());
            }

        } catch (Exception e2) {
            System.out.println("No se pudo reproducir la música: " + archivo);
            e2.printStackTrace();
        }
    }
}

    /**
     * Reproduce un sonido a partir de un archivo de sonido especificado.
     *
     * @param archivo Nombre del archivo de sonido sin la extensión (.wav).
     */
    public void sonido(String archivo) {
    try {
        String rutaArchivo = ruta + archivo + ".wav";

        new ProcessBuilder(
                "flatpak-spawn", "--host",
                "paplay", rutaArchivo
        ).start();

    } catch (Exception e1) {
        try {
            String rutaArchivo = ruta + archivo + ".wav";

            new ProcessBuilder(
                    "flatpak-spawn", "--host",
                    "aplay", "-q", rutaArchivo
            ).start();

        } catch (Exception e2) {
            System.out.println("No se pudo reproducir el sonido: " + archivo);
            e2.printStackTrace();
        }
    }
}


    /**
     * Método principal que inicia la aplicación.
     *
     * @param args Los argumentos de la línea de comandos (no se utilizan en
     * este caso).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }


    /** @hidden */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton cine;
    private javax.swing.JLabel cuantosJugadores;
    private javax.swing.JButton cuatroJugadores;
    private javax.swing.JButton culturaGeneral;
    private javax.swing.JButton dosJugadores;
    private javax.swing.JLabel eligeLasCategorias;
    private javax.swing.JButton empezar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel logo;
    private javax.swing.JButton multijugador;
    private javax.swing.JButton paises;
    private javax.swing.JButton salir;
    private javax.swing.JButton sorpresa;
    private javax.swing.JButton tresJugadores;
    private javax.swing.JButton unJugador;
    // End of variables declaration//GEN-END:variables
}
